### ISSUE TITLE
Consistent screenshots

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#11]
Every page in the Hello World tutorial should consistently finish with `<section class="see-yourself">` section, followed by a screenshot/GIF.

Currently, only some pages have "see yourself" sections and only some have screenshots.

@Mackiovello I don't know if you know, animated GIFs can be easily created using LICEcap.

**Comment by ErlendLandro** [comment]
I understand why you would want that. The issue with having a see-yourself at the end of each page is that it gets repetitive. I think we can take for granted that they will check the application they create, though at certain stages we might want to draw their attention to something specific. 

It's also the case that the UI changes between many parts are minimal and thus, the screenshot doesn't add any value.

The GIF's idea is excellent. I'll add that on the parts where it's relevant.

**Comment by ErlendLandro** [comment]
Screenshots or GIFs are added to all pages except for 6 and 7. 6 because of the buggy button, and 7 since there's no visual change there.

**Comment by warpech** [comment]
> Screenshots or GIFs are added to all pages except for 6 and 7. 6 because of the buggy button, and 7 since there's no visual change there.

I thought that your workaround (`this.Expense.Clear()`) fixes the bug actually?
