### ISSUE TITLE
Comments to "Initialize the Database – Hello World Part 1"

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#12]
Definitely some introduction before "Part 1" is needed. Looking forward to see it when it's done. This might be done as a separate article or as few paragraphs of introduction in the same paragraph.

I would rename this section from "Initialize the Database" to "Create a database class".

> Establish a new class Person with the attribute [Database] inside the HelloWorld namespace.

After this sentence, I propose to write something like "This tells Starcounter to make any instance of this class persistent."

> "which will push this person into the database"

Change to "which will keep this person in the database".

Add a screenshot or animated GIF of using SQL in Administrator.

**Comment by ErlendLandro** [comment]
All these remarks are now addressed.
