### ISSUE TITLE
Comments to "Create a Real Time UI – Hello World Part 2"

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#13]
> To make Polymer work.

I propose to change it to: "To make use of Polymer's template engine"

> previously empty json file

Change to "previously empty JSON file"

> Start the application with F5 and open the HelloWorld file in localhost:8181/#/databases/default. You should see the name of your Person appear.

I think that there is a simpler way. "Start the application with F5 and go to http://localhost:8080/HelloWorld in your web browser. You should see the name of your Person appear."

**Comment by ErlendLandro** [comment]
Fixed!
