### ISSUE TITLE
Comments to "First Interactive UI – Hello World Part 3"

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#14]
I think that the `PersonJson.json` snippet should include the curly braces.

> The ::input syntax is similar to an event listener. It registers every time there is a new input and updates the JSON accordingly.

I would change it to: The `::input` declaration sets up an event listener. It updates the JSON as you type in the HTML input element.

> trigger an handler

"trigger a handler"

> Open your application by pressing F5and clicking open in the Starcounter Administrator.

I think that this should be exactly the same info as in "Step 2". 

> Try hitting save and then check out your database with SQL.

I like this! I think this should be a separate paragraph though, with a screenshot or animated GIF.

**Comment by ErlendLandro** [comment]
Done!
