### ISSUE TITLE
Comments on "Calculated Name – Hello World Part 4"

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#15]
I think that "Computed properties" would be a better name for this page.

> Right now, our application does not display the name as we type. Would it not be better to let the code-behind calculate the full name and then display that to the user without any delay? Let us do that!

I think that this introduction misses some of the key benefits. I propose to rewrite it: 

"Starcounter allows you to use computed properties in your data model. Computing values on the fly is often as fast as accessing cached data and brings additional benefits. It allows you to save memory and always be sure that you get the current value.

Let's compute the `FullName` of a person from their `FirstName` and `LastName` and display it without any delay!"

> concatenating together 

"concatenating"

> Our next step is to add an expense tracker. That will take a little more effort.

I propose: "Our next step is to practice working on multiple object instances and relations. We will turn our app into a simple expense tracker."

**Comment by ErlendLandro** [comment]
Done
