### ISSUE TITLE
Comments on "Expense Tracker – Hello World Part 5"

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#16]
Maybe let's add a brief introduction in the beginning? Something along the lines of:

> Let's practice working on multiple object instances and relations. We will turn our app into a simple expense tracker. We will learn how to compose a complex view using multiple small partial views.

Regarding the list of steps:

> 1. Add a new Starcounter HTML template with dom-bind in the HelloWorld folder together with PersonJson.html.
> 2. Add a new Starcounter Typed JSON with Code-behind file to the HelloWorld project together with PersonJson.json and PersonJson.json.cs.
> 3. Name all of these files ExpenseJson.

I think this will be better:
1. Add a new Starcounter HTML template with dom-bind in the HelloWorld folder together with PersonJson.html. Name it `ExpenseJson.html`.
2. Add a new Starcounter Typed JSON with Code-behind file to the HelloWorld project together with PersonJson.json and PersonJson.json.cs. Name it `ExpenseJson.json`.

> starcounter-include is basically a placeholder for another template

I would prefer: `starcounter-include` is an insertion point for another template

> We will also add using System and using System.Collections.Generic at the same time.

This does not make sense here. Actually it also does not make sense in the program (my bad). It must be some artifact from previous versions. Let's remove `using System` and `using System.Collections.Generic` from the program and from the tutorial text.

**Comment by ErlendLandro** [comment]
Done, I'll also remove <code>using System</code> and <code>using System.Collections.Generic</code> from the program.
