### ISSUE TITLE
Comments on "Simplifying the Data Model – Hello World Part 7"

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#17]
I propose to rename this page to "Use a shared data model"

> Currently, we define every attribute of our database classes. That is a waste. C# is an object-oriented language, so we can inherit the needed attributes from an already defined database class. Starcounter has provided a tool for that called Simplified. To get this data model into our program we need to take two steps:

This is interesting to see your introduction to the page. But it misses the most important reason. I propose to rewrite the above paragraph to be:

"In the previous steps, we have used a data model declared using `[Database]` classes directly in `Program.cs`. This is nice for prototyping, but does not get us very far in terms of code and data reuse. 

Starcounter has a unique ability to allow multiple apps to work on the same data. We do this by putting the data model into a separate project and loading it as a DLL in all apps that are interested.

It is also possible to map two unrelated data models, but this Tutorial does not cover that.

Starcounter comes with a built in data model called "Simplified". Using it or inheriting from it allows you to integrate your apps with our sample and prefab apps, without extensive data mapping."

**Comment by ErlendLandro** [comment]
Adopted the new intro with some modifications
