### ISSUE TITLE
Comments on "Mapper App for Images – Hello World Part 8"

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#18]
> an external app called Images

"an prefab app called Images"

> from github

"from GitHub"

> In addition, you have to add using Starcounter.Internal to the beginning of the same file.

To set up mapping for the "Images" app, you have to declare the code in context of that app using `StarcounterEnvironment.RunWithinApplication`. This method becomes available after adding `using Starcounter.Internal` to the beginning of the file.

**Comment by ErlendLandro** [comment]
Fixed
