### ISSUE TITLE
Comments on "UI Blending – Hello World Part 9"

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#19]
You did your best in writing this page, but actually I admit that I chose only one of the possible ways to do the blending in my code.

Actually it is possible to use a completely different method of setting up the blended UI:
- When Launcher is running, click on the paint brush icon in the top right corner
- Double click the input field that says "css selector for partial to edit"
- Select `[partial-id="/sc/htmlmerger?HelloWorld=/HelloWorld/ExpenseJson.html&Images=/Images/viewmodels/ConceptPage.html"]` from the list
- paste the HTML from the sample file to the ACE Editor there and press Save

The method that I describe above is possible to do by point-and-click in runtime, as opposed to the current method that requires Git Bash and cURL. 

Which is better? I don't know, perhaps both should be presented in the tutorial?

**Comment by ErlendLandro** [comment]
I'll give it one more try. This approach is way better and should be the only method that's explained.

Installing git bash adds unnecessary complexity.

**Comment by warpech** [comment]
I still think that Git Bash/cURL approach needs to be explained somewhere. We can move it to Guides.

**Comment by ErlendLandro** [comment]
It's now updated to use the point-and-click method
