### ISSUE TITLE
Add links to source code

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#20]
@Mackiovello what do you think about this: 

At the end of each step in the tutorial text, add link to this repository with information about how to checkout the code for this specific step.

**Comment by ErlendLandro** [comment]
I've done that, but a little differently. If you click on the file name above each code block it will lead you to the right file in the right commit in GitHub. We could also add the link to the whole repository at the end of each page if there's a need for that

**Comment by warpech** [comment]
I've seen that, but I think that is non-obvious. A more explicit link at the bottom would help those who miss the snippet.

**Comment by ErlendLandro** [comment]
Okay, I'll add it right away

**Comment by ErlendLandro** [comment]
Link to source code added to all parts
