### ISSUE TITLE
Make GIF's work in all web browsers 

### ISSUE THREAD

**Issue by ErlendLandro** [warpech/HelloWorld#23]
Gif's does currently only work in some browsers if you open them up in full screen. 

Try to find a solution where the GIF's play automatically without needing to click on them.

**Comment by warpech** [comment]
In what browsers GIFs do not play automatically?

**Comment by ErlendLandro** [comment]
Chrome on OSX, Edge, and IE are those I know

**Comment by warpech** [comment]
Perhaps it's because the GIF is not inserted as full size?

This causes WordPress to convert GIF into a smaller resolution, static image

**Comment by ErlendLandro** [comment]
That's possible. I'll try to scale down the size of a GIF and try if that works.

**Comment by ErlendLandro** [comment]
Scaling down worked! Pages now load faster and the GIFs work in all web browsers.
