### ISSUE TITLE
Rename the first page

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#24]
Perhaps it would be good to rename the URL from "Hello World Introduction"?

Some suggestions:
- Hello World
- Hello World project

WDYT?

Also, I recommend to change the URL from `http://starcounter.io/tutorials/hello-world-introduction-2/` to `http://starcounter.io/tutorials/hello-world/`

**Comment by ErlendLandro** [comment]
You're completely right, I'll fix that right away

**Comment by ErlendLandro** [comment]
Url and title of Hello World page is now fixed
