### ISSUE TITLE
Opening images in other tabs?

### ISSUE THREAD

**Issue by Joltrix** [warpech/HelloWorld#25]
Question.

At the moment, when an image is clicked, it changes the page to the image.

Would it perhaps be better to make the image open on a separate tab?

@Mackiovello @warpech what do you guys think?

**Comment by warpech** [comment]
I think that the good default behaviour on the web is to open the image in the same tab. Right click or CTRL + click allows to open in a new tab.

**But** it would be better if the images opened in some form of lightbox instead of replacing the full page.

**Comment by ErlendLandro** [comment]
Would something like this be sufficient? 
<img width="528" alt="screenshot" src="https://cloud.githubusercontent.com/assets/19392292/19726998/d596db74-9b8d-11e6-9f35-a24ba63d8773.png">

**Comment by Joltrix** [comment]
Yeah, that would look a lot better! :D

**Comment by ErlendLandro** [comment]
Lightboxes like the one above have now been added to all images and GIFs.

**Comment by warpech** [comment]
Does not work for me... Perhaps you need to clear WP Super Cache?

**Comment by ErlendLandro** [comment]
Can you try one more time? I cleared the WP Super Cache

**Comment by warpech** [comment]
Yeah, works now!
