### ISSUE TITLE
Add "Experimental" notice to Steps 8 and 9

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#28]
As @mtornwall pointed out in https://github.com/Starcounter/CompanyTrack/issues/242#issuecomment-256587065, Steps 8 and 9 are using an approach that is likely to be changed in future.

I think that we owe it to the developer to explain this. Something along the lines of:

> The APIs presented on this page are **experimental**. Blending of apps' user interfaces is an essential feature of Starcounter, but the way to achieve it is likely to be changed in future. Please follow our [blog](http://starcounter.io/blog/) to learn more.

@Mackiovello can you add the above notice to Steps 8 and 9? Feel free to improve the message.

**Comment by ErlendLandro** [comment]
I've added the following notice on steps 8 and 9:

<strong>Disclaimer</strong>
The APIs used in this step are experimental. We consider blending of different application's user interfaces to be an essential feature. Currently, it's functional but not optimal. We are working hard to develop exceptional blending that might require the steps outlined here to be changed. Feel free to follow our <a href="http://starcounter.io/blog/">blog</a> to get information about these changes and more.

If you feel like that's good enough, then you can close this issue

**Comment by mtornwall** [comment]
Sounds good to me. 👍

**Comment by warpech** [comment]
I would remove this part: "Currently, it's functional but not optimal.". Self criticism is good, but doesn't look good in docs :)

**Comment by ErlendLandro** [comment]
> I would remove this part: "Currently, it's functional but not optimal.". Self criticism is good, but doesn't look good in docs :)

That part is now removed 😃

**Comment by warpech** [comment]
Thanks! Closing as done
