### ISSUE TITLE
Improve the tutorial intro

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#31]
This paragraph feels a little odd: 

> This is not your ordinary Hello World tutorial. Instead of only checking whether your setup is correct, as the goal with other Hello World tutorials usually is, we will also help you to understand Starcounter’s features and how it can help you as a developer to create fast, modular applications in a fraction of the time it would usually take.

We will guide you through the process of creating a database, making an interactive UI, and blending different applications seamlessly together. 

As suggested by Ted, it could be rewritten to sound more appealing.

I like how this tutorial begins: https://spatialos.improbable.io/docs/reference/8.0/tutorials/pirates/overview

**Comment by ErlendLandro** [comment]
Is this more how you would like it?

> In this “Hello World” tutorial you will learn how to use the essential features of Starcounter by building an expense tracker complete with a database, interactive UI, real-time syncing, and seamless integration with other applications.
> 
> In the first two steps, you will create the simplest possible application that binds the database to the view.
> 
> The four steps following that will be where we create our expense tracker by establishing our UI and building in some functionality that allows us to do CRUD operations on the database.
> 
> In the last three steps will consist of making our expense tracker integrate with other applications in a seamless fashion.
> 
> This is hopefully how it will look when you are done:

**Comment by ErlendLandro** [comment]
It's now published in a somewhat reworded fashion [here](https://starcounter.io/tutorials/hello-world/)

**Comment by ErlendLandro** [comment]
Close since intro is improved

**Comment by warpech** [comment]
Just one more remark - please use more confidence! 

> This is ~~hopefully~~ how it will look when you are done

**Comment by ErlendLandro** [comment]
Intro is now more confident
