### ISSUE TITLE
Dead link in "Create a Real Time UI"

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#32]
In the step "Create a Real Time UI", the link to **"Learn about Polymer bindings"** is a 404:

![screen shot 2016-11-07 at 15 28 22](https://cloud.githubusercontent.com/assets/566463/20061141/dad5b2f2-a4fe-11e6-9872-3c410f56edcc.png)

**Comment by ErlendLandro** [comment]
Link is now fixed
