### ISSUE TITLE
"Create a Real Time UI" needs to mention thin-client view-model rendering

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#33]
As Ted pointed out, the "Create a Real Time UI" jumps to creating files without explaining what we are really doing:

> It’s not clear what these files are for at the beginning; can you at least give me a hint as to why these files will be necessary? That way I’m at least thinking about it while I follow your steps to create them. Also, in this file, you mention Polymer, but I don’t think it’s mentioned anywhere before this—I didn’t realize that was in play until just now.

I think that we need to explain in **one paragraph** that we are defining a view-model in C# with a real time view in HTML.

Some description might be borrowed from:

- https://starcounter.io/tutorials/1-introduction-to-part-1/1-4-create-the-view-model/
- https://starcounter.io/tutorials/1-introduction-to-part-1/1-5-render-json-in-html/
- https://starcounter.io/guides/web/creating-a-browser-page/

**Comment by ErlendLandro** [comment]
Short explanation added to the beginning of the document.

Open this issue again if it's not satisfactory.

> To create a user interface (UI) we need to add a view-model and a corresponding view. The view-model will act as a representation of the view and as a midpoint between the view and the database.
> 
> Let's create our file structure that contains our view (HTML) and view-model (JSON). If you follow these steps you will have the right files to build the UI:
