### ISSUE TITLE
“First Interactive UI” should better explain code-behind sync

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#34]
On the page "First Interactive UI" there is a paragraph that advocates the use of server-side view-models in a quite unconvincing way.

This was reported by Ted.

I propose to rewrite this paragraph:

> Notice here that our application logic is written in the code-behind and not in the view. The purpose of that is to completely remove the need to write so-called “glue code” that otherwise would translate changes between the view, view-model, and model. The benefits of this are many. For this tutorial, we will not focus further on that topic, instead, we just have to remember that all our application logic should be written in the code-behind.

With something like: 

> With server-side view-models you don't have to write a single line of "glue code" to update the view in HTML. Any change in the view-model made in C# will be automatically propagated to the client by PuppetJs, which in turn automatically renders thanks to Polymer's data binding. This saves you from creating single-purpose REST APIs, need for double validation of user input, etc.

Good to put some link in the right column that explains this in details.

**Comment by ErlendLandro** [comment]
Paragraph changed to the following:

> With server-side view-models, you don't have to write a single line of "glue code" to update the view in HTML. Any change in the view-model made in C# will instantly be synced to the client using PuppetJs, which in turn automatically renders because of Polymer's data bindings. This saves you from creating single-purpose REST APIs, need for double validation of user input, and more.
