### ISSUE TITLE
List of already created expenses is not rendered

### ISSUE THREAD

**Issue by tomalec** [warpech/HelloWorld#36]
Once I have added some expenses to http://localhost:8080/HelloWorld (step 6) and reload the page, my expenses are no longer there.

Is it a "know simplification" not to write too much code?
If so, I find it pretty confusing as  even though there are no expenses my balance is >0, and they will appear after clicking "Cancel" button.

![expenses](https://cloud.githubusercontent.com/assets/17435/20066017/72bb7d16-a510-11e6-843c-76896c8155dc.gif)

**Comment by ErlendLandro** [comment]
This issue is now fixed both in the tutorial and in the code on branch `tutorial-20161130` that is now set to default.

It was as simple as changing `if (person.Spendings == null)` to `if (person.Spendings != null)`
