### ISSUE TITLE
Need for Launcher needs to me either removed or clearly communicated

### ISSUE THREAD

**Issue by tomalec** [warpech/HelloWorld#37]
As due to https://github.com/Starcounter/Starcounter/issues/3915 Launcher needs to be running to execute the curl with layouts, I think it would be good to mention this at 
https://github.com/StarcounterSamples/HelloWorld/commit/d511f5abc1c09952ba005fb9d3bf9d410055140e#diff-0cbf7f0b9cd8fbd93b45f23f30787aa1R10

As I spent almost an hour wondering why I get 
```
URI not found: POST /sc/partial/composition?key=%2Fsc%2Fhtmlmerger%3FHelloWorld%3D%2FHelloWorld%2FExpenseJson.html%26Images%3D%2FImages%2Fviewmodels%2FConceptPage.html&ver=
```

**Comment by ErlendLandro** [comment]
Since we're not using cURL in the HelloWorld tutorial, is this necessary? 

It's explained in the [guides](https://starcounter.io/guides/web/import-html-compositions/) where we link from the tutorial.

**Comment by tomalec** [comment]
Sorry IMissed those guides, as I was just reading code and commits from repo. But, then I would have even more comments ;)
1. I'd add the link to this guide in this repo's README.md,
2. I'd move the disclaimer to the REST API article as this one is experimental, and Shadow DOM is pretty stable,
3. In general, I'd like to remove the need for the Launcher for both cases (see issues in Rebels Lounge)

**Comment by warpech** [comment]
Since Launcher 6.0.0, the need for Launcher is gone.

But still you will get the error as described in first comment if CompositionEditor app is not running.

@Mackiovello can you please update the description of step 9 that you need CompositionEditor to import the composition from file. You will need CompositionProvider and CompositionEditor apps running to edit the composition live in web browser after pressing CTRL+E.

Future work:

- CompositionProvider will be enabled in Starcounter (https://github.com/Starcounter/Starcounter/issues/4019)
- @alemoi says HTMLComposition API cannot be enabled by default. This is why CompositionEditor is needed to import the composition. (https://github.com/Starcounter/Starcounter/issues/3915)

**Comment by ErlendLandro** [comment]
@warpech are you sure about that? CompositionProvider requires 2.3 and I believe that the tutorial should work on starcounter stable. Please correct me if I'm wrong.

**Comment by warpech** [comment]
Very good question! Luckily, CompositionProvider and CompositionEditor also work with 2.2, they were just not built for 2.2. I have made a build and uploaded it to the old Warehouse.

**Comment by ErlendLandro** [comment]
Wow! I tried it now, it's a beautiful solution! 

Just a tiny thing, I would love to have a small exit button in the top right corner. Other than that, this feels way more intuitive than using the launcher.

I'll incorporate it into the tutorial right away.

**Comment by warpech** [comment]
> Just a tiny thing, I would love to have a small exit button in the top right corner. Other than that, this feels way more intuitive than using the launcher.

Feel free to add an issue in https://github.com/Starcounter/CompositionEditor

Btw you can press Esc or CTRL+E to close the editor. I will add this to README

**Comment by ErlendLandro** [comment]
The tutorial is now updated, so this issue can be considered solved.

> Feel free to add an issue in https://github.com/Starcounter/CompositionEditor

Will do

**Comment by warpech** [comment]
Great, thanks! In future I think we should recommend installing Images, CompositionEditor and CompositionProvider from Warehouse instead of from GitHub.

**Comment by ErlendLandro** [comment]
> Great, thanks! In future I think we should recommend installing Images, CompositionEditor and CompositionProvider from Warehouse instead of from GitHub.

The tutorial is now updated to encourage the use of the App Warehouse.
