### ISSUE TITLE
How to create src solution folder in solution?

### ISSUE THREAD

**Issue by SenerDemiral** [warpech/HelloWorld#38]
In:  https://starcounter.io/hello-world/create-a-database-class-hello-world-part-1/
Create a Database Class

>Create a folder named src inside the HelloWorld solution. Drag the HelloWorld project into this folder. We will later add another project, so this makes it easier for us to organize.

How?

**How to: Add Solution Folders to a Solution** document describe as;
> In Solution Explorer, right-click the solution or a Solution Folder, choose Add, and then choose New Solution Folder.

But it does not create windows folder! But your source have **src** folder.

> Solution Folders are an organizational tool in Solution Explorer; corresponding Windows folders are not created. We recommend that you organize your projects on disk in the same way that you organize them in the solution.

I think, i missed something.

**Comment by SenerDemiral** [comment]
Create New Solution in VS

>File -> New -> Project
Template: Other Project Types -> Visual Studio Solutions -> Blank Solution
Location: C:\someDirectory
Solution Name: StarcounterHelloWorld

Add new project to solution

>Solution Explorer -> Solution -> Add -> New Project
Name: HelloWorld
Location: C:\someDirectory\StarcounterHelloWorld\\**src**

**Comment by ErlendLandro** [comment]
I'm not quite sure if I understand your question.
This is how you would create a src folder in VS:
![srcfoldergif](https://cloud.githubusercontent.com/assets/19392292/20874561/5b25847c-bab3-11e6-863b-7c0f6288cd45.gif)

This step is not entirely necessary. I'll look into it and see if we can make this easier to follow. For now, you can skip that step since it doesn't actually change anything about the way the code runs.

Thank you for your question!

**Comment by SenerDemiral** [comment]
Thank you, 
We, newbies stumble such details.
If it is not necessary, please extract below paragraph.
> Create a folder named src inside the HelloWorld solution. Drag the HelloWorld project into this folder. We will later add another project, so this makes it easier for us to organize.

This src is logical folder not OS folder/directory.
But in your source code (GitHub) it is real OS folder.
Never mind!

**Comment by ErlendLandro** [comment]
Need for the `src` folder is removed and references to it in the tutorial are removed
