### ISSUE TITLE
HtmlFromJsonProvider(), PartialToStandaloneHtmlProvider(), SessionOptions.PatchVersioning

### ISSUE THREAD

**Issue by dan31** [warpech/HelloWorld#39]
Yeah yeah I know we've been discussing this in iterations again and again, and I do not discover anything new there, and this is not about a particular tutorial but the problem in general, but we really need to continue actively thinking until the problem is resolved. Step 1 in tutorial is supernice and simple with db classes and transaction, but then Step 2 "Adding some Gui" is like "BOOOOF" in my face:

```
Application.Current.Use(new HtmlFromJsonProvider());
Application.Current.Use(new PartialToStandaloneHtmlProvider());
   Handle.GET("/HelloWorld", () => {
      var json = new PersonJson();
      json.Data = Db.SQL<Person>("SELECT p FROM Person p WHERE p.LastName = ?", "Doe").First;
      json.Session = new Session(SessionOptions.PatchVersioning);
```

I could never understand libraries and frameworks where complexity is "end in itself" (maybe they are so beloved because they create so many wonderful jobs to tackle this complexity). Unfortunately this is the impression I get from ```.Use``` and explicit session creation.

I believe the problem is more generic there - i.e. the problem is how to make managing the session (shared state and transaction) really simple, straightforward, magic-less. The feeling is partially because names are way too verbose, but also because the session and "app" itself feels like something "added afterwards", not-so-native.

I already had this analogy. When I go to a new restaurant, I wish to get "Chef Recommends" meal, because I don't want to study pages of menu and make choice myself. I am tired in the evening and just want to relax with a glass of wine enjoying chefs best choice. It doesn't mean that I cannot ask chef to not use sauce - in fact it should be possible. But then they tell me "No, you should do all the choices yourself, spend next 3 hours studying menu and ingredients, all for you man, we know you'd manage to cope with it, you are strong fella", something like that (the picture is called "A cake for Linux' birthday"):

![image](https://cloud.githubusercontent.com/assets/7162535/21070978/477a7c2e-be92-11e6-9502-550c0628ec70.png)

Do you share my feeling? :)

**Comment by ErlendLandro** [comment]
This may be a little naive; would it be feasible to implement implicit session creation? Or rather, are there cases when you would not like to have sessions?

Regarding the tutorial, I completely agree. That whole block of code is pretty much glossed over because it would be a distraction to have a lengthy description of HtmlFromJsonProvider, sessions and so on. On the other hand, now it's confusing since there is this big block of code that's not really explained. I'm not sure what to do, and to be honest, I don't completely understand this stuff either.

**Comment by dan31** [comment]
@Mackiovello we don't have a solution still, but we now have more bright minds like you to help us all solve the puzzle. As you say, it might be the only way - to provide implicit defaults for applications with GUI.  As a developer, I don't want to get those with backend-only apps, but I definitely appreciate those defaults present which I would use for full apps (blendable) 95% of the time. I would say it might be two types of projects - Starcounter backend service (no defaults, as it is only backend) and Starcounter app (blendable).

But then it turns out providing such defaults (in any future, we are only dreaming about different options now) are in the palaces of weaving. (CC @per-samuelsson, let's see what he thinks about this, he isn't newbie to this ongoing discussion either)

**Comment by ErlendLandro** [comment]
Archiving
