### ISSUE TITLE
What is PartialToStandaloneHtmlProvider?

### ISSUE THREAD

**Issue by SenerDemiral** [warpech/HelloWorld#40]
> Application.Current.Use(new PartialToStandaloneHtmlProvider()); sends the necessary files to inititate our WebSocket connection.

Is it?
or
If firstPage does not contain `<!DOCTYPE html>`, Starcounter sends implicit HTML template that contains code to bootstrap.
```
﻿<!DOCTYPE html>
<html>
<head>
....bootstrap.....
</head>
<body>
--->> firstPage 
</body>
</html>

**Comment by ErlendLandro** [comment]
@per-samuelsson do you know more about this?

**Comment by warpech** [comment]
This middleware is explained as an inline comment: https://github.com/Starcounter/Starcounter/blob/1576adc7545a36d9541908854570a510696eef80/src/Starcounter/Middleware/PartialToStandaloneHtmlProvider.cs#L7-L21

**Comment by warpech** [comment]
@SenerDemiral anything we should add in your opinion? 

Both your answers are generally the same thing. I think that our explanation that you quote is quite enough for a "Hello World" tutorial, but it should be followed by a link to a more detailed explanation (like presented by you). 

I have made an internal note to improve the docs.

**Comment by SenerDemiral** [comment]
Thanks @warpech.
If PartialToStandaloneHtmlProvider() are used no need to write classic `index.html`.
Necessary files automatically sends to client.
