### ISSUE TITLE
Record and upload tutorial videos

### ISSUE THREAD

**Issue by ErlendLandro** [warpech/HelloWorld#41]
### Create Hello World video tutorials

To back up the written tutorials I'll make video tutorials for those that prefer watching instead of reading. The code will be the same, although the content might be a little bit more in-depth in the videos. The goal is to keep them below 10 minutes. 

The steps to achieve this are:
1. Get pop-filter or find studio time
2. Write a short script for the video
3. Record a draft video
4. Upload video on youtube so that people with a link can view
5. Add link here for people to review
6. Re-record video according to feedback
7. Upload to youtube with public access 
8. Link to video in the corresponding part on .io
9. Repeat step 2-8 with all the parts

My proposed timeline is to have all the videos done by January 7th. 

Part one has been recorded and reviewed by @ubbeK. It will be remade with better sound equipment once the pop-filter arrives.

Are there any suggestions to keep in mind?

Progress tracker:
- [x] [Create a Database Class](https://www.youtube.com/watch?v=HyRoctAmYdU) (final)
- [x] [Create a Real Time UI](https://www.youtube.com/watch?v=aPg-akjidDc) (final)
- [x] [First Interactive UI](https://www.youtube.com/watch?v=WcbeORJKf2M) (final)
- [x] [Computed Properties](https://www.youtube.com/watch?v=xrMQeR2cxJc) (final)
- [x] [Expense Tracker](https://www.youtube.com/watch?v=5ZbuRxlME8s) (final)
- [x] [Cancel and Delete](https://www.youtube.com/watch?v=7Hmn3Hc3vXg) (final)
- [x] [Using a Shared Data Model](https://www.youtube.com/watch?v=-vFNwCS1GMk) (final)
- [x] [Mapper App for Images](https://www.youtube.com/watch?v=vHti2SeKUTs) (final)
- [ ] [UI Blending](https://www.youtube.com/watch?v=3orUKLaZqfk) (draft, needs to be redone without Launcher)

**Comment by ErlendLandro** [comment]
The first draft is now up on Youtube as an unlisted video for you to watch. Please take a look [here](https://youtu.be/oXwX2ug75os) and say what you think.

The obvious thing I have to do is to get a license for Camtasia to get rid of the watermark, it also seems like the volume is far too low. That is an easy fix though.

@ubbeK @Joltrix @warpech

**Comment by dan31** [comment]
@Mackiovello I recommend native streaming to youtube using https://obsproject.com/. If you want to check out how easy this can be done, join one of our weekly meetings every Wednesday 12-30!

**Comment by ubbeK** [comment]
Much better structure!

Does Starcounter have any official intro which we may use in the tutorials?

**Comment by Joltrix** [comment]
Good job! :D Except for the sound issue (and the obvious watermark lol), I couldn't find anything bad with it! :)

1 thing though, not sure if its only me, but I had a hard time understanding/hearing "your title" (when you introduced yourself :/ ) Especially when your title is something "unheard of", so just kinda be clearer with that I guess :D

And like @ubbeK said, It would be really cool if we had some official intro to reuse for all starcounter videos! :D

**Comment by ErlendLandro** [comment]
> 1 thing though, not sure if its only me, but I had a hard time understanding/hearing "your title" (when you introduced yourself :/ ) Especially when your title is something "unheard of", so just kinda be clearer with that I guess :D

Good catch! I'll redo the first part tomorrow to be clearer. With that I'll also fix the two other issues and post the new version here to confirm that it look good.

> And like @ubbeK said, It would be really cool if we had some official intro to reuse for all starcounter videos! :D

That's right, it would give it a more professional look. I'm thinking of using a small part of the [video on .com](https://www.youtube.com/watch?v=pLEcoqkuu6A) with the fancy lasers and stuff followed by the Starcounter logo. Not sure if that's what we're aiming for though.

**Comment by Joltrix** [comment]
@Mackiovello 

> That's right, it would give it a more professional look. I'm thinking of using a small part of the video on .com with the fancy lasers and stuff followed by the Starcounter logo. Not sure if that's what we're aiming for though.

Hmm, You can try, as long as it's not too long  :O An intro, at least in my eyes, would be something like, 1-3 seconds, maybe max 5. and kinda shows of the starcounter logo somehow (either an animation that "forms" the logo, or just an animation that "causes the logo to appear" or something similar)

For example: Check the first 5 seconds of this [video](https://www.youtube.com/watch?v=WQqRKsHI0oA)

**Comment by ErlendLandro** [comment]
> For example: Check the first 5 seconds of this video

That's a good example. I could easily pull together some simple animation where the Starcounter logo comes flying in or something like that. It would possibly be the best type of intro since it's not a distraction. This should probably be coupled with some neat little sound as well.

**Comment by ErlendLandro** [comment]
The final first part is now uploaded in a good enough shape to be considered done, although if you have some remarks for future videos, I'll gladly listen to them. The sound volume is greatly increased, there is a simple intro with the Starcounter logo, and I've added some annotations to increase clarity. 

The video can be found [here](https://www.youtube.com/watch?v=l47yiXb-zmw).

**Comment by ubbeK** [comment]
@Mackiovello Nice, I think we should involve the Christer Bengtsson, the Marketer, regarding the decision of an intro. Does he have GitHub?

**Comment by dan31** [comment]
@Mackiovello I don't think we need to explain how to download VS - if you do, then you also need to explain how to install it 😈 I believe that saying smth like "We will use Visual Studio 2015 Community in this video" should be fine. I emphasize on that, because Starcounter is not a Microsoft product.

**Comment by ErlendLandro** [comment]
The video is taken down since it seems like I have to do some more work on it.

@Christerben is there a short Starcounter video intro available? Or do we have to make something?

@dan31 got it. I'll make this change as soon as possible.

**Comment by dan31** [comment]
@Mackiovello I think in general the video is great and I like the way you explain and talk, I suggest it can be made shorter / more dynamic. People are inclined to consume big amount of small videos today. After you have it, don't hesitate to use youtube editor to cut some unnecessary pauses or speed up some fragments with typing only.

**Comment by warpech** [comment]
I didn't manage to see the video, but once again I recommend buying Screenflow or Camtasia for @Mackiovello for great looking screencasts.

**Comment by ErlendLandro** [comment]
@warpech I've bought Camtasia, to that's fixed.

@dan31 I'm aware that some people enjoy their videos to be somewhat fast-paced, though that's not the case for everyone. There's always the option of speeding up the video in the youtube player. You are right that I should try to cut some pauses and maybe look if I can speed up parts of it.

Do I speak too slow? I know I have a tendency to speak fast, so I consciously spoke slower when recording. Is that the right call?

**Comment by ErlendLandro** [comment]
Here's the new version of the first part: [https://www.youtube.com/watch?v=s4GKDbhq2B0](https://www.youtube.com/watch?v=s4GKDbhq2B0)

Here's what I've done:
1. Increased the pace of the video significantly.
2. Cut the part where I described how to get VS etc.
3. Added a nice little intro.
4. Improved the outro.
5. Cut out all the waiting part of the tutorial. 

Please take a look and say what you think.

Is it too fast? Do I explain too little?

**Comment by warpech** [comment]
Good idea with the drawings - you present the result of the whole HelloWorld before beginning. Amazing drawing skills :) And everything else is amazing, too!

I am missing something about what is the topic of this video, because you only mention what is the topic of the whole series.

Around second 0:25, it would be good to add on-video captions with links to Starcounter and Visual Studio.

Regarding the scope of the explanation - I think it is right in the sweet spot!

**Comment by ErlendLandro** [comment]
> Good idea with the drawings - you present the result of the whole HelloWorld before beginning. Amazing drawing skills :) And everything else is amazing, too!

Thank you! That's good to hear.

> I am missing something about what is the topic of this video, because you only mention what is the topic of the whole series.

I knew I missed something. Working on a fix right now.

> Around second 0:25, it would be good to add on-video captions with links to Starcounter and Visual Studio.

The goal was to do this, though it turned out that Youtube has pretty harsh restrictions regarding linking to outside websites using on-video captions, that's why I'm adding them in the description instead. Hopefully, that's acceptable. I'll go ahead and add the URL in an on-video caption as well.

**Comment by warpech** [comment]
I suggest that you introduce yourself with your full name, not just first name. At least in the written form on screen.

**Comment by ErlendLandro** [comment]
> I suggest that you introduce yourself with your full name, not just first name. At least in the written form on screen.

Fixed!

@ubbeK @Joltrix 
Could I get some feedback from you guys before I upload the new version with the fixes that Marcin proposed?

**Comment by Joltrix** [comment]
Okay, I've watched it a few times to kinda form an opinion :P

The first thing I noticed.. was the music xD what's up with the music? Would it be possible to change the music to something else? even just something ambient, or a ping noise would suffice.

How come you use the white "intro", but with a black border. It feels so.. "copy-pasted". would it be possible to kinda change the "theme-color" to white? And kinda use a white background for all the current black screens? That would make it more.. "complete" or you know, give the video a common theme based off of the intro. ( Cause I'm thinking it's easier to edit all the black screens, vs editing the intro right?)

And if possible. instead of doing the flip from intro > video, and from video > outro, perhaps it would be better to use a fade?, or a switch + fade in?, or a simple "hard switch" (which would look better if you removed the black edges from the video and made them white for example).

so, conclusion for the "appearance": Try to give it a more "whole" look. Use the whole window instead of "most of the screen" with a black border.

Content wise, I liked it! :D You covered all the "points", while not talking too fast, while simultaneously keeping the video so short! Good job~, But be prepared for all the "Whats a Developer evangelist?" comments haha :D

Oh, you could also say something towards the end, instead of just going to the outro. something small, maybe something like: "So now that you know XXXX, we can move on to doing/learning XXXXX, which will be covered in the next part", leading up to the outro.

I realize a lot of this is just a matter of preference and design. So if someone else has any better ideas, or if people prefer it how it is now, then just ignore me :D

**Comment by Christerben** [comment]
I’ve watched the video a couple of times now. Overall impression is that it’s brilliant! I really like the drawings.

About the border that Dimitris had some thoughts on. I think it needs to stay, to emphasize the feeling of a cube rotating. I agree with Marcin, you should have your full name on the screen but it’s enough to speak only your first name.

The music could be more ”futuristic”, if you know what I mean? The sound quality is a little bit uneven (especially noticeable when you move on to VS), but I guess you’re planning to do a whole new soundtrack to give it a more professional feel?

A really good video, on the whole. I hope we will get the opportunity to do both shorter and longer clips in the future as well.


[photo]
[https://s3.amazonaws.com/images.wisestamp.com/icons_32/facebook.png]<https://www.facebook.com/StarcounterDB/> [https://s3.amazonaws.com/images.wisestamp.com/icons_32/linkedin.png] <https://www.linkedin.com/company/starcounterdb>  [https://s3.amazonaws.com/images.wisestamp.com/icons_32/twitter.png] <https://twitter.com/StarcounterDB>
         Christer Bengtsson || Marketing Coordinator
+46 73 788 96 12<http://t.sidekickopen55.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW-gY64zKlYVQBb2Y56dStCf2-JMT-02?si=X-SIG-APPLE-NOKEY&pi=8F71530B-5836-4470-86D0-463AA94B2205&t=http%3A%2F%2Ft%2Esidekickopen55%2Ecom%2Fe1t%2Fc%2F5%2Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%2DgY64zKlYVQBb2Y56dStCf2%2DJMT%2D02%3Fsi%3DX%2DSIG%2DAPPLE%2DNOKEY%26pi%3D933EB8FF%2DBDA5%2D4644%2DB3FF%2D9117AF12413F%26t%3Dhttp%253A%252F%252Ft%252Esidekickopen54%252Ecom%252Fe1t%252Fc%252F5%252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%252DgY64zKlYVQBb2Y56dStCf2%252DJMT%252D02%253Fsi%253DX%2DSIG%2DAPPLE%2DNOKEY%2526pi%253DE9813137%252DA95D%252D4994%252D9892%252D39A47DCF486F%2526t%253Dhttp%25253A%25252F%25252Ft%25252Esidekickopen51%25252Ecom%25252Fe1t%25252Fc%25252F5%25252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%25252DgY64zKlYVQBb2Y56dStCf2%25252DJMT%25252D02%25253Fsi%25253DX%25252DSIG%25252DAPPLE%25252DNOKEY%252526pi%25253DE60A8C49%25252D695E%25252D4E4D%25252D9ED7%25252D2044EB4D773E%252526t%25253Dhttp%2525253A%2525252F%2525252Ft%2525252Esidekickopen42%2525252Ecom%2525252Fe1t%2525252Fc%2525252F5%2525252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%2525252DgY64zKlYVQBb2Y56dStCf2%2525252DJMT%2525252D02%2525253Fsi%2525253DX%25252DSIG%25252DAPPLE%25252DNOKEY%25252526pi%2525253DAAB9D957%2525252DC78B%2525252D41D0%2525252DACB9%2525252D73F20BB47B41%25252526t%2525253Dhttp%252525253A%252525252F%252525252Ft%252525252Esidekickopen42%252525252Ecom%252525252Fe1t%252525252Fc%252525252F5%252525252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%252525252DgY64zKlYVQBb2Y56dStCf2%252525252DJMT%252525252D02%252525253Fsi%252525253DX%252525252DSIG%252525252DAPPLE%252525252DNOKEY%2525252526pi%252525253DE894EC10%252525252DD5B5%252525252D44A6%252525252DA816%252525252D4D46AFBA1CD3%2525252526t%252525253Dhttp%25252525253A%25252525252F%25252525252Ft%25252525252Esidekickopen42%25252525252Ecom%25252525252Fe1t%25252525252Fc%25252525252F5%25252525252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%25252525252DgY64zKlYVQBb2Y56dStCf2%25252525252DJMT%25252525252D02%25252525253Fsi%25252525253DX%25252525252DSIG%25252525252DAPPLE%25252525252DNOKEY%252525252526pi%25252525253D7ECA8E1E%25252525252DD6EF%25252525252D4236%25252525252DB494%25252525252D05EE98F67C4C%252525252526t%25252525253Dtel%2525252525253A%2525252525252B46%25252073%252520788%25252096%25252012> | christer.bengtsson@starcounter.com<mailto:thamwika@starcounter.com>
www.starcounter.com<http://www.starcounter.com> | www.starcounter.io<http://www.starcounter.io>
Nybrokajen 5, 111 48 Stockholm, Sweden



20 dec. 2016 kl. 11:52 skrev Erlend <notifications@github.com<mailto:notifications@github.com>>:


Here's the new version of the first part: https://www.youtube.com/watch?v=s4GKDbhq2B0

Here's what I've done:

  1.  Increased the pace of the video significantly.
  2.  Cut the part where I described how to get VS etc.
  3.  Added a nice little intro.
  4.  Improved the outro.
  5.  Cut out all the waiting part of the tutorial.

Please take a look and say what you think.

Is it too fast? Do I explain too little?

**Comment by ErlendLandro** [comment]
## Answer to @Joltrix 
> The first thing I noticed.. was the music xD what's up with the music? Would it be possible to change the music to something else? even just something ambient, or a ping noise would suffice.

I searched around for an eternity looking for open source music. Do you know a good place to look? There are a ton of piano solos in minor scales, though that can't be what we want. This connects to what @Christerben says in that:
> The music could be more ”futuristic”, if you know what I mean? The sound quality is a little bit uneven (especially noticeable when you move on to VS), but I guess you’re planning to do a whole new soundtrack to give it a more professional feel?

The whole sound aspect is way more challenging than I expected. From what both of you are saying, the ultimate solution would be to put together some kind of simple electronic track that can be used for all the videos. I could otherwise do an acoustic track but I'm not sure if that gives the right feel.

> How come you use the white "intro", but with a black border. It feels so.. "copy-pasted". would it be possible to kinda change the "theme-color" to white? And kinda use a white background for all the current black screens? That would make it more.. "complete" or you know, give the video a common theme based off of the intro. ( Cause I'm thinking it's easier to edit all the black screens, vs editing the intro right?)

This is an interesting point. I'm a much bigger fan of black themes, although I might need to adapt to the intro in this case. The issue with this is that the coding sections are dark. It would be nice if everything could be dark to match this. Unfortunately, we only have this one intro. I'll try making it white and see how it looks. In that case, I would also have to drag out the intro to cover the whole screen. 

> And if possible. instead of doing the flip from intro > video, and from video > outro, perhaps it would be better to use a fade?, or a switch + fade in?, or a simple "hard switch" (which would look better if you removed the black edges from the video and made them white for example).

That's an easy fix. I'll try and see how it looks.

> Oh, you could also say something towards the end, instead of just going to the outro. something small, maybe something like: "So now that you know XXXX, we can move on to doing/learning XXXXX, which will be covered in the next part", leading up to the outro.

Fair point. I'll do that.

## Answer to @Christerben

> I’ve watched the video a couple of times now. Overall impression is that it’s brilliant! I really like the drawings.

Thank you!

> I agree with Marcin, you should have your full name on the screen but it’s enough to speak only your first name.

Agree, it's fixed now.

> The sound quality is a little bit uneven (especially noticeable when you move on to VS)

You're completely right in that. I'm not sure why it's that way since I'm using the exact same equipment. I'll look further into it to see what I can do.

> A really good video, on the whole. I hope we will get the opportunity to do both shorter and longer clips in the future as well.

I hope so too! I've already learned a ton from this video. The upcoming ones will probably be produced much faster and require less feedback.

**Comment by ErlendLandro** [comment]
It's improving!

Here's a new version with responses to your comments: [https://www.youtube.com/watch?v=0JhPJJZhG8c](https://www.youtube.com/watch?v=0JhPJJZhG8c)

How's the music in this one @Joltrix ?

There are still two issues:
1. The music has a Creative Commons license that does not allow commercial use. Even If I'm just using 3 sec of a 4 min sound file, I believe I have to find something else that is similar if we feel that the sound of this one is better.
2. There is still a slight variation of the sound quality. I've located the issue. It's possible to record everything again to fix it. If you feel like it's crucial, then I'll do that, though from my standpoint it doesn't seem like that big of a deal. The quality of the sound will be constant in future videos.

**Comment by Christerben** [comment]
Looks good!

1. Have you checked these sites? https://creativecommons.org/about/program-areas/arts-culture/arts-culture-resources/music-communities/

2. The sound variation is much smaller now. I think it is acceptable.


[photo]
[https://s3.amazonaws.com/images.wisestamp.com/icons_32/facebook.png]<https://www.facebook.com/StarcounterDB/> [https://s3.amazonaws.com/images.wisestamp.com/icons_32/linkedin.png] <https://www.linkedin.com/company/starcounterdb>  [https://s3.amazonaws.com/images.wisestamp.com/icons_32/twitter.png] <https://twitter.com/StarcounterDB>
         Christer Bengtsson || Marketing Coordinator
+46 73 788 96 12<http://t.sidekickopen55.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW-gY64zKlYVQBb2Y56dStCf2-JMT-02?si=X-SIG-APPLE-NOKEY&pi=8F71530B-5836-4470-86D0-463AA94B2205&t=http%3A%2F%2Ft%2Esidekickopen55%2Ecom%2Fe1t%2Fc%2F5%2Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%2DgY64zKlYVQBb2Y56dStCf2%2DJMT%2D02%3Fsi%3DX%2DSIG%2DAPPLE%2DNOKEY%26pi%3D933EB8FF%2DBDA5%2D4644%2DB3FF%2D9117AF12413F%26t%3Dhttp%253A%252F%252Ft%252Esidekickopen54%252Ecom%252Fe1t%252Fc%252F5%252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%252DgY64zKlYVQBb2Y56dStCf2%252DJMT%252D02%253Fsi%253DX%2DSIG%2DAPPLE%2DNOKEY%2526pi%253DE9813137%252DA95D%252D4994%252D9892%252D39A47DCF486F%2526t%253Dhttp%25253A%25252F%25252Ft%25252Esidekickopen51%25252Ecom%25252Fe1t%25252Fc%25252F5%25252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%25252DgY64zKlYVQBb2Y56dStCf2%25252DJMT%25252D02%25253Fsi%25253DX%25252DSIG%25252DAPPLE%25252DNOKEY%252526pi%25253DE60A8C49%25252D695E%25252D4E4D%25252D9ED7%25252D2044EB4D773E%252526t%25253Dhttp%2525253A%2525252F%2525252Ft%2525252Esidekickopen42%2525252Ecom%2525252Fe1t%2525252Fc%2525252F5%2525252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%2525252DgY64zKlYVQBb2Y56dStCf2%2525252DJMT%2525252D02%2525253Fsi%2525253DX%25252DSIG%25252DAPPLE%25252DNOKEY%25252526pi%2525253DAAB9D957%2525252DC78B%2525252D41D0%2525252DACB9%2525252D73F20BB47B41%25252526t%2525253Dhttp%252525253A%252525252F%252525252Ft%252525252Esidekickopen42%252525252Ecom%252525252Fe1t%252525252Fc%252525252F5%252525252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%252525252DgY64zKlYVQBb2Y56dStCf2%252525252DJMT%252525252D02%252525253Fsi%252525253DX%252525252DSIG%252525252DAPPLE%252525252DNOKEY%2525252526pi%252525253DE894EC10%252525252DD5B5%252525252D44A6%252525252DA816%252525252D4D46AFBA1CD3%2525252526t%252525253Dhttp%25252525253A%25252525252F%25252525252Ft%25252525252Esidekickopen42%25252525252Ecom%25252525252Fe1t%25252525252Fc%25252525252F5%25252525252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%25252525252DgY64zKlYVQBb2Y56dStCf2%25252525252DJMT%25252525252D02%25252525253Fsi%25252525253DX%25252525252DSIG%25252525252DAPPLE%25252525252DNOKEY%252525252526pi%25252525253D7ECA8E1E%25252525252DD6EF%25252525252D4236%25252525252DB494%25252525252D05EE98F67C4C%252525252526t%25252525253Dtel%2525252525253A%2525252525252B46%25252073%252520788%25252096%25252012> | christer.bengtsson@starcounter.com<mailto:thamwika@starcounter.com>
www.starcounter.com<http://www.starcounter.com> | www.starcounter.io<http://www.starcounter.io>
Nybrokajen 5, 111 48 Stockholm, Sweden



20 dec. 2016 kl. 15:23 skrev Erlend <notifications@github.com<mailto:notifications@github.com>>:


It's improving!

Here's a new version with responses to your comments: https://www.youtube.com/watch?v=0JhPJJZhG8c

How's the music in this one @Joltrix<https://github.com/Joltrix> ?

There are still two issues:

  1.  The music has a Creative Commons license that does not allow commercial use. Even If I'm just using 3 sec of a 4 min sound file, I believe I have to find something else that is similar if we feel that the sound of this one is better.
  2.  There is still a slight variation of the sound quality. I've located the issue. It's possible to record everything again to fix it. If you feel like it's crucial, then I'll do that, though from my standpoint it doesn't seem like that big of a deal. The quality of the sound will be constant in future videos.

**Comment by Joltrix** [comment]
oooh!! I think this is a lot better!! Specially the intro, the music and the transition to the "hello world part 1" screen.

1 thing though, how come the borders to the orange boxes is green xD? Wouldn't it look better with.. something more dark greyish, or black or something like that~?

If its not too much work, I'd love to see how everything would look with a bit shorter fade in. (don't get me wrong, it looks awesome right now! But I think it can get even better ;) )

Another thing, I'm not a big fan of the "box-effect", which remains on the transition from the "hello world screen" to the writing field. You could use some sort of fade out, and then "directly" start writing. considering it will fade out into a white screen and then continue with the writing (which is on a white screen), So I'd recommend a fast fadeout there! :D 

Also, Is the sound necessary in the outro? We could have it end right at the "see you in the next video" *end*, but both work! :)

But again, good job!

**Comment by ErlendLandro** [comment]
> Have you checked these sites? https://creativecommons.org/about/program-areas/arts-culture/arts-culture-resources/music-communities/

No, I haven't. I'll continue looking there. Thank you!

>1 thing though, how come the borders to the orange boxes is green xD? Wouldn't it look better with.. something more dark greyish, or black or something like that~?

Didn't even notice that. I'll fix it right away.

>Another thing, I'm not a big fan of the "box-effect", which remains on the transition from the "hello world screen" to the writing field. You could use some sort of fade out, and then "directly" start writing. considering it will fade out into a white screen and then continue with the writing (which is on a white screen), So I'd recommend a fast fadeout there! :D

I tried that now, it looks much better.

>Also, Is the sound necessary in the outro? We could have it end right at the "see you in the next video" end, but both work! :)

I was conflicted about that. Though now it's gone.

The last thing to do is to find some music that I can use legally. Then I think we can consider this one done.

**Comment by ErlendLandro** [comment]
Hopefully, this will be the final version. The transitions are improved, there are no more green boxes, and the sound is now used legally. 

I'm aware that there are a couple of seconds extra after I stop talking. That is to give people time to click that big beautiful button. If you feel like that should be removed, it's really easy to shave of using the Youtube editor.

Take a look here: [https://www.youtube.com/watch?v=e2PTsfsAfWE](https://www.youtube.com/watch?v=e2PTsfsAfWE) (for the thousandth time 😄  )

**Comment by Joltrix** [comment]
> I'm aware that there are a couple of seconds extra after I stop talking. That is to give people time to click that big beautiful button. If you feel like that should be removed, it's really easy to shave of using the Youtube editor.

Nah, it's fine like that! :)

Good job~ This looks really good :D I don't have any more "complaints" haha :P

**Comment by ErlendLandro** [comment]
Part two of the draft is now [here](https://www.youtube.com/watch?v=HLPI-GDOOXo)

Please take a look and state your opinion.

**Comment by ErlendLandro** [comment]
Draft of part three is now [here](https://www.youtube.com/watch?v=YUjoClV3qTE)

**Comment by Joltrix** [comment]
Good job, once again :D  

There were only a few things that I think can be improved.

1.when you talk about the dollar sign, you simply say that you make the property "changeable". Which isn't wrong per say but I think it would be easier to understand if you were to say "By adding the dollar sign we make this property two-way-bindable, which allows us to edit this value from: both the client side, and the server side" or something similar.

2. When you are going to add the handler to the save button, you say "...The save button, only increments an arbitrary integer, **lets change that**..."

Which I wouldn't say is completely correct, considering the save still does just that, even after the handler have been added. The difference is that we now have a handler that listens to the incrementation of that arbitrary integer :D

3. I think you could explain Db.Scope a bit "more", and maybe, make a reference: "Similarly to how we used db.transact (in the first video) before to add the person to the database we can use Db.Scope here to .... ... ... "

**Comment by ErlendLandro** [comment]
Thank you for the review @Joltrix, I'll deal with it as soon as possible.

Meanwhile, here's the draft for part 4: [https://www.youtube.com/watch?v=nB0HcYNuavQ](https://www.youtube.com/watch?v=nB0HcYNuavQ)

**Comment by ErlendLandro** [comment]
The latest versions of the first four drafts are linked in the first post. The latest points by @Joltrix are addressed. The goal is to be entirely done with the drafts by the end of the week.

**Comment by ErlendLandro** [comment]
This one took way more time than I expected. Here it is, [part 5](https://www.youtube.com/watch?v=MHqZ-RGSbrI)

**Comment by ErlendLandro** [comment]
[Part 6 is now up](https://www.youtube.com/watch?v=PfrQQBtNoT4)

**Comment by ErlendLandro** [comment]
[Part 7 is also uploaded](https://www.youtube.com/watch?v=KatVtS6fwUo)

**Comment by ubbeK** [comment]
In the second video, `SessionOptions.PatchVersioning` is quickly explained, but I cannot find any deeper explanation on starcounter.io. The same problem goes for `Application.Current.Use(new PartialToStandaloneHtmlProvider());`. Only `Application.Current.Use(new HtmlFromJsonProvider());` can be found at https://starcounter.io/guides/network/request-response-filters/#json-view-models-html-views

These are crucial parts for making an standalone app working and should be descibed somewhere at https://starcounter.io/guides/

**Comment by ErlendLandro** [comment]
@ubbeK this is directly related to #39. I completely agree that it seems to be an important component that is not described properly anywhere. It probably should be made into an issue at [TechComm](https://github.com/Starcounter/TechComm).

**EDIT**
There's actually an issue that's assigned to me about this. I'll take care of it after we've managed to migrate the documentation.

On another note, all the draft videos are now done and linked in the first post. Please take a look and comment on what's unclear and what can be improved. I realize that it's not perfect right now so don't be afraid to provide criticism.

**Comment by Joltrix** [comment]
@Mackiovello 

part 6:
You say that `Ibound<Person>` is needed. Is it perhaps possible to kinda, explain why its needed? or what it does?

also, at [2:30](https://youtu.be/PfrQQBtNoT4?t=149)~ you're writing things at the bottom of the screen (if the mouse is over the video window, the progressbar will block what you're writing), and when you fill the function, the content isn't visible.

Also, small tip: When creating a for loop for example by pressing tab tab, you can just press enter to enter the function (which will also get rid of the "yellowiish background highlighting")

Part 7:
Same as the previous, raise the "camera", or perhaps make your solution explorer window a bit smaller, so that the viewer can see everything you do. when you adjust the Copy Local property, its at the bottom of the screen.

And I think you can explain "Simplified" and "Something" a bit more, or give a brief explanation to what it is. Cause I can imagine this part being a bit confusing for beginners, at least I remember I found it quite confusing... xD

Same with the `Simplified.Ring1` and `Ring2` . You could for example say something like "in order to use XX we need to make a reference to Simplified.Ring1, cause this holds XX properties" or something similar. Something to kinda explain them instead of just "we need this to make this (somehow) magically work", but perhaps thats just me!

Part 9:
I felt that the whole "episode" was a bit rushed. In my opinion, the blending is one of the coolest things about starcounter, so personally, I think you should take a bit more time and explain it and show it off a bit more. Cause I think the viewers will have the following questions: "How does the blending actually work?" "What is that editor?" "Why did you write css in the browser and not in a css document/on the actual elements in the HTML?", "Did the styling get saved? Did it alter the code and added the css properties?", "Does the layout stay like this? Or is it only for this session"?

**Comment by ErlendLandro** [comment]
@Joltrix Thank you for the review! I'll look over your comments and make changes accordingly. What I'm struggling with is knowing how much people understand, i.e what is very Starcounter specific vs. what is common sense. Telling me what was confusing for you is very helpful!

**Comment by ErlendLandro** [comment]
The tutorial is now done and uploaded on Youtube. 

It is easily accessible in this playlist: [https://www.youtube.com/watch?v=HyRoctAmYdU&list=PLzBy_ulksMjDppM_aNr4DedQDwYd4PL9Q](https://www.youtube.com/watch?v=HyRoctAmYdU&list=PLzBy_ulksMjDppM_aNr4DedQDwYd4PL9Q)

I'll link this playlist from the introduction to the written Hello World tutorial and consider this issue done.
