### ISSUE TITLE
Create a HelloWorld fork with React

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#44]
This is an issue for investigation. What does it take to rebuild Hello World using React instead of Polymer on the client side. The solution should still use PuppetJs, so a PuppetJs-React bridge will be needed.

@alshakero - can you take this as a long term investigation? Please don't focus too much on it right now, but investigate when there are no other more important issues.

In future, I would also love to see a combination of Vue.js and PuppetJs.

**Comment by alshakero** [comment]
@warpech I'd love to, I'll report back here.

**Comment by mattiasmak** [comment]
I just want to point out that this is one of Colabers highest priorities right now. Calle will go to Starcounter HQ today and discuss this a bit further. Perhaps we can join forces on this one?

**Comment by warpech** [comment]
Great, let's discuss after Calle meets with Stefan.

**Comment by warpech** [comment]
Closing as done: 

- https://github.com/StarcounterSamples/HelloWorld-React
- https://github.com/StarcounterSamples/ReactNative-HelloWorld

In case of issues, please create issues there.
