### ISSUE TITLE
Update HelloWorld to use the "Trigger$" pattern in JSON

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#47]
Update HelloWorld to use the "XxxxTrigger$" pattern in JSON.

Relevant file: https://github.com/StarcounterApps/HelloWorld/blob/tutorial-20161222/src/HelloWorld/PersonJson.json

Properties: `Save$`, `Cancel$`, `DeleteAll$`

Discussion here: Starcounter/Guidelines#12

**Comment by ErlendLandro** [comment]
Fixed in 20170315 branch and set to default branch
