### ISSUE TITLE
Add batch files

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#48]
@Mackiovello do you think it would be a good idea to add `build.bat`, `run.bat` in HelloWorld?

For me this would surely make it easier to run. I think it could be added in commit of Step 1 without even mentioning it in the Tutorials.

**Comment by ErlendLandro** [comment]
I don't think it would be a problem to add. The links from the tutorial are still pointing to specific commits, adding it to the first commit where the solution etc. is created wouldn't pollute the repo. 

I can take care of it if you want.

**Comment by warpech** [comment]
Yes please. Just wait a second, cause I am adding another issue in few minutes.

**Comment by warpech** [comment]
Done https://github.com/StarcounterApps/HelloWorld/issues/49

**Comment by ErlendLandro** [comment]
Fixed
