### ISSUE TITLE
Step 9 does not work with current Images app

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#49]
Recently in the images app the URI that shows an Image of a something was changed.

In Step 9 (mapper apps), the line:

```cs
return Self.GET("/images/partials/concept/" + objectId);
```

needs to be changed to:

```cs
return Self.GET("/images/partials/somethings-edit/" + objectId);
```

----

Actually `/images/partials/somethings-edit/` displays a carousel with multiple items. It would be enough to have `/images/partials/somethings-single-edit/`, but we don't have that in the Images app now.

**Comment by ErlendLandro** [comment]
Fixed with https://github.com/StarcounterApps/HelloWorld/blob/tutorial-20170327/src/HelloWorldMapper/Program.cs
