### ISSUE TITLE
Problems with Transaction.Rollback and an array of items

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#5]
I need help to figure out a problem in the last step of Hello World. 

There is a `Cancel` button that rolls back a transaction. It fails two work in two cases. Case 1:
- Open `http://localhost:8080/helloworld`
- Press "Delete all expenses"
- Press "Save"
- Reload the page
- Press "Add new expense"
- Press "Cancel" - **Exception**

Case 2: 
- Open `http://localhost:8080/helloworld`
- Press "Delete all expenses"
- Press "Save"
- Reload the page
- Press "Add new expense"
- Press "Save"
- Reload the page
- Press "Delete all expenses"
- Press "Cancel" - **Exception**

@miyconst any idea how to solve this elegantly?

![bug](https://cloud.githubusercontent.com/assets/566463/15778607/83f51b68-2997-11e6-9de5-1360c4727da5.gif)

**Comment by miyconst** [comment]
@warpech the thing is that you have to manually remove items from the JSON collection after you remove the data objects.

**Comment by warpech** [comment]
The thing is that in case (1) I don't know how to do it...

In case (2) I think I do it, but it fails: https://github.com/StarcounterSamples/HelloWorld/blob/tutorial-20160603/PersonJson.json.cs#L26

**Comment by miyconst** [comment]
Let me take a look, looks like no easy solution in here.

**Comment by miyconst** [comment]
@warpech see my branch [`5-transaction-rollback`](https://github.com/StarcounterSamples/HelloWorld/tree/issue/5-transaction-rollback).

**Comment by miyconst** [comment]
It's very tricky to keep the array up to date, because each item is a partial. I can do that, but it will be a very dirty code, so the easiest way is to reload entire array on transaction rollback.

**Comment by warpech** [comment]
Thanks. I will merge this because it has huge advantage over my version - it works :)

Later we can discuss with the team if this pattern can be simplified.

**Comment by warpech** [comment]
Thanks once again @miyconst. Your change is pushed to https://github.com/StarcounterSamples/HelloWorld/tree/tutorial-20160606 (as step 6)

**Comment by miyconst** [comment]
Good. And thank you for taking care of the demo project.
