### ISSUE TITLE
Use declarative shadow dom

### ISSUE THREAD

**Issue by ErlendLandro** [warpech/HelloWorld#51]
Since we're now moving towards declarative shadow dom in our sample apps, it should also be applied to the tutorial. 

This is also needed for https://github.com/Starcounter/Docs/issues/69

I'll make a PR for it.

**Comment by ErlendLandro** [comment]
This will actually not work until https://github.com/Starcounter/Home/issues/89 is fixed.

I'm also wondering how to do this. Should declarative shadow dom be introduced in step 2? That seems early to me. It would also be possible to integrate into step 9 before we use blending.

CC @tomalec

**Comment by tomalec** [comment]
That's why I'd keep implicit slot names, then introduce it later on in step 9.

**Comment by ErlendLandro** [comment]
This is fixed with #52 and https://github.com/Starcounter/Docs/pull/93. Closing
