### ISSUE TITLE
Breakout mapping and blending part into its own tutorial

### ISSUE THREAD

**Issue by ErlendLandro** [warpech/HelloWorld#52]
After listening to some people that have done the tutorial, it seems like the mapping and blending part doesn't provide any real value the way it is right now. 

It presents concepts that are barely touched upon in the [mapping and blending](https://docs.starcounter.io/guides/mapping-and-blending/) part of the guides, which is the documentation that is supposed to be in-depth. To those that have read our white papers and other writing it's also contradictory; why do we say that Starcounter is free of "glue code" when we need to a completely new project to make two simple apps work together?

What I would like to see, and what has been discussed before, is to separate the learning of building individual apps with the process of integrating these apps with one another. Partly because they, in some degree, target different people, but also because they are very separate concepts.  Currently, this leads to confusion instead of clarity.

My proposed solution is to make the tutorial focused on building a standalone application that, of course, can easily be integrated with other applications. To teach mapping and blending I would suggest using the sample apps to our advantage. This would be more of a conceptual tutorial than a practical one. The guides would then complement it with how mapping and blending work in code.

CC @warpech

**Comment by warpech** [comment]
This is a good suggestion, I think we should go for it. 

Though, in the "mapping and blending tutorial" (MnB) we must provide a clear goal in what to build. In Hello World the goal was to:

- learn HTTP handlers
- learn JSON with code behind
- learn binding to HTML
- learn buliding data models
- learn nesting of views

In mapping an blending the goal should be:

- share data with other apps
- share screen with other apps
- blend the apps on the screen

Do you think that it matters to continue the MnB from the Hello World? Maybe not? 

Then we will not have to use a shared data model in Hello World. But we will have to create a new context in MnB, maybe through explaining how to build one of our sample apps from scratch. Something simple, like Skyper, comes to mind.

**Comment by ErlendLandro** [comment]
Good to hear! 

I completely agree with you regarding the goals. The question I'm asking myself is: does this even need a tutorial? 

Let's break down the goals that you outline:

> share data with other apps

Right now, that simply means using a shared data model. That is partly covered in [the guides](https://docs.starcounter.io/guides/mapping-and-blending/sharing-data/). That page should be expanded to give some short code examples and how to create a new shared data model. Other than that, it's really nothing new.

> share screen with other apps

This is now being covered by the new [blending documentation](https://github.com/Starcounter/Docs/pull/71). If that page was expanded with some practical examples, that base would be covered as well.

> blend the apps on the screen

This is not really covered at all. I'm not sure at the state of this at the moment, but it should be documented. 

From this, we can see that these concepts are yet to be properly explained in the guides, or anywhere else. That should be the first priority. It's also essential that we have a nice suite of apps that properly use what we teach.

The main issue with the mapping and blending part of the tutorial is that it's somewhat misleading and uses old concepts such as ontology mapping. Because of that, I suggest removing it as soon as possible so that we don't teach people the wrong things.

It would be nice to have a step by step tutorial on how to use mapping and blending. Right now, I don't think we're quite ready for it. It would be something to build when we have a solid understanding ourselves of how it should work and the old API's are properly phased out.

My suggested plan is to:
1. Delete the mapping and blending parts from the current tutorial
2. Expand the page that explains how to share data with other apps
3. Figure out how to blend the apps on the screen and document it
4. Provide examples of how to do server-side blending
5. Ensure that we have a group of apps that can be started from the warehouse and work seamlessly together. This would give people an actual example of how mapping and blending can work.

**Comment by warpech** [comment]
> The question I'm asking myself is: does this even need a tutorial?

Tutorial is like a workbook (practical, hands-on, often the first contact). Guides is like a student's book (theoretical, often the second contact). I think it is super important to have sharing data in both places, because you cannot simply have blending without it.

Since mapping and blending is the most important (and also the most mind-bending) aspect of Starcounter, I cannot imagine how could we not have a tutorial for that.

**Comment by ErlendLandro** [comment]
Okay, I'll create a suggestion for two minimal apps that use blending and then build a tutorial out of it. The tutorial clearly needs to explain every step from the data sharing to visual blending. I would like to remove the current mapping and blending parts of the tutorial as soon as it's done since the features it uses are deprecated.

**Comment by ErlendLandro** [comment]
> Since mapping and blending is the most important (and also the most mind-bending) aspect of Starcounter, I cannot imagine how could we not have a tutorial for that.

A tutorial for mapping and blending will soon be created. Meanwhile, I would like to remove the mapping and blending parts from the tutorial. It's both misleading and doesn't actually work. I'll have a suggestion for the new tutorial in time for the next TechComm task force meeting the 30th.

**Comment by ErlendLandro** [comment]
An update regarding this:

I've built on the current HelloWorld and created another minimal app to demonstrate blending. Looking over the documentation, the [sharing screen page](https://docs.starcounter.io/guides/blending/sharing-screen/) can also be replaced with this upcoming tutorial. 

I'm currently stuck on trying to show how to map objects to one anther. The specific issue is that I'm not able to observe changes to the database in another app. I've tried commit hooks. The relevant people have been contacted to get some help figuring it out.

If this is resolved within a day or two, a draft to the tutorial should be ready for the next Technical Communication task force meeting the 31st.

**Comment by ErlendLandro** [comment]
This new tutorial would also resolve https://github.com/Starcounter/Docs/issues/69 and https://github.com/StarcounterApps/HelloWorld/issues/51.

Additionally, it would only pertain to server side blending and sharing of data. I.e no client side blending tutorial yet.

**Comment by ErlendLandro** [comment]
Okay, I now have a working demo of blending and database sharing in action:
![blendingattempt](https://cloud.githubusercontent.com/assets/19392292/26294476/5099f61a-3ec4-11e7-9fa7-03f90ad50003.gif)

The "remove" buttons and "remove duplicates" button are from another app. I'm not confident that it's the optimal solution, anyway, could you please take a look @warpech? 

Keep in mind that there's error handling or anything like that. It just works for this limited use case to demonstrate data sharing and blending.

**Comment by warpech** [comment]
I will review that shortly.

Meanwhile: as suggested in https://github.com/StarcounterApps/MultiplePagesDemo/issues/2#issuecomment-303715275, I think that the blending tutorial should include navigation between views.

**Comment by ErlendLandro** [comment]
I've made a new attempt with [PetHealthSystem](https://github.com/StarcounterApps/PetHealthSystem).

Please take a look. The steps are divided into specific commits. The plan is that the person taking the tutorial can start out with two applications that are not prepared for blending and then go through the step of setting up blending, a shared database, and then finally blend them.

**Comment by tomalec** [comment]
@Mackiovello can we remove it from Blending Task Force scope? Is there anything we as a Blending Team need to provide for that?

**Comment by ErlendLandro** [comment]
> @Mackiovello can we remove it from Blending Task Force scope? Is there anything we as a Blending Team need to provide for that?

Yes, it can be removed from the Blending Task Force scope
