### ISSUE TITLE
Add integration with Images

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#6]
As the last step (7), it should be possible to add an image of the expense instead of text description.

The image should be added using the Images app.

**Comment by warpech** [comment]
Ideally, the HelloWorld map should use its own data model and _map_ it to Simplified data model, which is used by Images.

**Comment by per-samuelsson** [comment]
@warpech 

Beside defining the actual mappings (and run Images app, etc), what is needed in terms of infrastructure to complete this? We must introduce a launcher here, right?

**Comment by warpech** [comment]
No, the only APIs involved are `UriMapping.OntologyMap`. Only two apps should be started (+ a mapper app).

**Comment by per-samuelsson** [comment]
Ah, ok, so we _do_ support (default) blending / sharing screen without something like a launcher? And that's our goal here?

**Comment by warpech** [comment]
Yes, definitely. Two apps is enough to blend. Launcher just gives a common UI features for switching between apps (like menu bar, search input, etc).

**Comment by per-samuelsson** [comment]
And finally (for now): we want to use data mapping here (`DbMapping.*`)? Isn't that still supposed to be under the radar (and the alternative being shared data model)?

**Comment by warpech** [comment]
> And finally (for now): we want to use data mapping here (`DbMapping.*`)? Isn't that still supposed to be under the radar (and the alternative being shared data model)?

That is a question to @dan31. @dan31 please advise here.

If we don't use `DbMapping.*`, then last step of HelloWorld needs to switch the data model to Simplified.

**Comment by warpech** [comment]
This is related to: https://github.com/Starcounter/Starcounter/issues/3538

**Comment by warpech** [comment]
After lots of trial and error, I have managed to integrate HelloWorld with Images in two short steps.

See commits described `step 8` and `step 9` in https://github.com/StarcounterSamples/HelloWorld/tree/tutorial-20161018

Not jawdropping, but I think it is acceptable for the start and concludes the HelloWorld tutorial well.

Screenshot:

![2016-10-19 02_39_36-launcher](https://cloud.githubusercontent.com/assets/566463/19501501/6eb49afa-95a6-11e6-9cd7-6aa8705887be.png)

cc @Mackiovello

**Comment by warpech** [comment]
Closing as done.
