### ISSUE TITLE
About integration with Images

### ISSUE THREAD

**Issue by per-samuelsson** [warpech/HelloWorld#8]
Can we take a step back, to a more high-level view?

Here's a discussion I'd like to have, and I'm using #6 (`HelloWorld` + `Images`) as the context, but it should apply to any kind of app inter operable scenario.

I'm the developer of `Hello World`. I've completed it up to step 6 in the tutorial. By chance, I find the `Images` app in an app store. I try it out, and find that it should be nice to support images to be attached to expenses.

What's our story here? What's needed, and by whom - can I complete everything by reusing a certain partial of `Images`, and if so, what info would I need? It's URI pattern? Would there have to be any mapping made inside the `Images` app (I hope and think not).

What changes if `Images` is open/closed source? What changes if it builds upon `Simplified` compared to if it employs it's local model?

I guess this topic is not something easily answered simply, but let's see if we can get something out of it at least.

**Comment by warpech** [comment]
### What's the incentive of mapping and blending with a 3rdparty app?

As the application developer, you need to focus on working on the parts that are essential to the application that your are building. If someone else has already part of the job, better than you can with your resources, why don't you just use his work and focus on the missing parts? If someone else did something that was not on your original backlog, but can be integrated in less than 3 hours and it greatly improves the perceived value of the application, that is a viable option.

I think this is the same what sells NPM modules when you are using Node.js. Node.js is a great application runtime, but 50% of its appeal comes from the package ecosystem, not the runtime itself.

### How might it work for real?

The way I imagine this - `Images` comes with a list of partials available for mapping (listed in `README.md` or so). Each partial expects a particular data model. Therefore, mapping and blending it with your app requires:
- a the same or equivalent data model in your app
- if the data model is not the same, data model mappings in a `.map.cs` file, done according to the mapping instrucitons in Images `README.md`
- an partial insertion point in your app
- partial URI mappings in a `.map.cs` file, done according to the mapping instrucitons in Images `README.md`

Does it sound reasonable?

---

BTW there's a great chance for @Starcounter-Jack to plug in with his response.

**Comment by warpech** [comment]
@per-samuelsson I am closing this as answered. @Mackiovello has written the text that explains the steps that I made in code. It is available in WordPress admin panel as a draft.

I know that mapping HelloWorld to Images is far from ideal, but hey - we have something that works! The current code and text of HelloWorld should be the beginning of the discussion how we can improve that.

**Comment by per-samuelsson** [comment]
> @per-samuelsson I am closing this as answered. 

Sounds like the right thing to do.

> I know that mapping HelloWorld to Images is far from ideal, but hey - we have something that works! 

🎉 👍 🎈
