### ISSUE TITLE
Broken layout editor for step 9

### ISSUE THREAD

**Issue by ErlendLandro** [warpech/HelloWorld#9]
In step 9 you are supposed to either use a curl command or the built-in layout editor. Because of the [broken layout editor](https://github.com/StarcounterPrefabs/Launcher/issues/202) with a non-editable input screen and disabled buttons, you cannot use it.

Is there a simple way of working around this as this seems to be the most accessible way of doing it?

**Comment by warpech** [comment]
@Mackiovello can you please provide the steps to reproduce the error? For me it works when I follow the steps given in https://github.com/StarcounterSamples/HelloWorld/issues/19#issue-184823790
